const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const allowedService=new Set(['quality','tickets','surveys']);
const allowedPeriod=new Set(['daily','weekly','monthly','annual']);
function clean(body){
  const employee_name=String(body.employee_name??body.name??'').trim();
  const service=String(body.service??'').trim();
  const period=String(body.period??'').trim();
  const quality=Number(body.quality),csat=Number(body.csat),productivity=Number(body.productivity??body.prod);
  if(!employee_name||!allowedService.has(service)||!allowedPeriod.has(period)||!Number.isFinite(quality)||quality<0||quality>100||!Number.isFinite(csat)||csat<0||csat>100||!Number.isFinite(productivity)||productivity<0) return null;
  const employee_id=String(body.employee_id??'').trim(),supervisor_name=String(body.supervisor_name??'').trim(),record_date=String(body.record_date??'').trim(),notes=String(body.notes??'').trim(),service_metrics=JSON.stringify(body.service_metrics&&typeof body.service_metrics==='object'?body.service_metrics:{});
  if(employee_id.length>30||supervisor_name.length>80||notes.length>300||record_date.length>10)return null;
  return {employee_name,employee_id,supervisor_name,record_date,notes,service_metrics,service,period,quality,csat,productivity:Math.round(productivity)};
}
async function init(DB){
 await DB.prepare("CREATE TABLE IF NOT EXISTS governance_users (username TEXT PRIMARY KEY COLLATE NOCASE,password TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();
 await DB.prepare("CREATE TABLE IF NOT EXISTS governance_audit (id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT NOT NULL,action TEXT NOT NULL,record_id INTEGER,details TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();
 await DB.prepare("INSERT OR IGNORE INTO governance_users(username,password,role,active) VALUES ('SuperAdmin','SuperAdmin','superadmin',1),('Admin','Admin','admin',1)").run();
 try{await DB.prepare("ALTER TABLE governance_records ADD COLUMN saved_by TEXT DEFAULT 'Admin'").run()}catch(e){}
 try{await DB.prepare("ALTER TABLE governance_records ADD COLUMN employee_id TEXT DEFAULT ''").run()}catch(e){}
 try{await DB.prepare("ALTER TABLE governance_records ADD COLUMN supervisor_name TEXT DEFAULT ''").run()}catch(e){}
 try{await DB.prepare("ALTER TABLE governance_records ADD COLUMN record_date TEXT DEFAULT ''").run()}catch(e){}
 try{await DB.prepare("ALTER TABLE governance_records ADD COLUMN notes TEXT DEFAULT ''").run()}catch(e){}
 try{await DB.prepare("ALTER TABLE governance_records ADD COLUMN service_metrics TEXT DEFAULT '{}'").run()}catch(e){}
 try{await DB.prepare("ALTER TABLE governance_users ADD COLUMN supervisor_username TEXT DEFAULT ''").run()}catch(e){}
 // One-time compatible role migration for legacy accounts.
 await DB.prepare("UPDATE governance_users SET role='supervisor',updated_at=CURRENT_TIMESTAMP WHERE role='admin'").run();
 await DB.prepare("UPDATE governance_users SET role='employee',updated_at=CURRENT_TIMESTAMP WHERE role='user'").run();
 // Preserve the existing pilot team relationship when both legacy accounts exist.
 await DB.prepare("UPDATE governance_users SET supervisor_username='Admin',updated_at=CURRENT_TIMESTAMP WHERE username='fgodairy' COLLATE NOCASE AND role='employee' AND COALESCE(supervisor_username,'')='' AND EXISTS(SELECT 1 FROM governance_users WHERE username='Admin' COLLATE NOCASE AND role='supervisor')").run();
 await DB.prepare("CREATE TABLE IF NOT EXISTS governance_evaluations (id INTEGER PRIMARY KEY AUTOINCREMENT,supervisor_username TEXT NOT NULL,employee_username TEXT NOT NULL,score REAL NOT NULL,notes TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();
 await DB.prepare("CREATE TABLE IF NOT EXISTS governance_reports (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,report_type TEXT NOT NULL DEFAULT 'snapshot',owner_username TEXT NOT NULL,owner_role TEXT NOT NULL,payload TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();
}
function row(r){return {id:r.id,name:r.employee_name,employee_name:r.employee_name,employee_id:r.employee_id||'',supervisor_name:r.supervisor_name||'',record_date:r.record_date||'',notes:r.notes||'',service_metrics:(()=>{try{return JSON.parse(r.service_metrics||'{}')}catch(e){return {}}})(),service:r.service,period:r.period,quality:r.quality,csat:r.csat,prod:r.productivity,productivity:r.productivity,date:r.updated_at,created_at:r.created_at,updated_at:r.updated_at,savedBy:r.saved_by||'Admin'};}
async function audit(DB,u,a,id,d){await DB.prepare('INSERT INTO governance_audit(username,action,record_id,details) VALUES (?,?,?,?)').bind(u||'Admin',a,id||null,JSON.stringify(d||{})).run()}
export default {
 async fetch(request,env){
  const url=new URL(request.url);
  try{
   await init(env.DB);
   if(url.pathname==='/api/health') return json({ok:true,service:'governance-dashboard',time:new Date().toISOString()});
   if(url.pathname==='/api/auth/login'&&request.method==='POST'){const b=await request.json(),name=String(b.username||'').trim(),pass=String(b.password||''),u=await env.DB.prepare('SELECT username,role FROM governance_users WHERE username=? AND password=? AND active=1').bind(name,pass).first();if(u){try{await audit(env.DB,u.username,'LOGIN_SUCCESS',null,{role:u.role})}catch(auditError){}return json({ok:true,user:u})}try{const known=await env.DB.prepare('SELECT username,role,active FROM governance_users WHERE username=? COLLATE NOCASE').bind(name).first();await audit(env.DB,name||'Unknown','LOGIN_FAILED',null,{attempted_username:name||'(blank)',account_exists:!!known,account_active:known?!!known.active:null})}catch(auditError){}return json({ok:false,error:'Invalid credentials'},401)}
   if(url.pathname==='/api/users'&&request.method==='GET'){const q=await env.DB.prepare("SELECT username,role,active,supervisor_username,created_at,updated_at FROM governance_users ORDER BY username").all();return json({ok:true,users:q.results||[]})}
   if(url.pathname==='/api/users'&&request.method==='POST'){const b=await request.json(),name=String(b.username||'').trim(),pass=String(b.password||'');if(!name||!pass)return json({ok:false,error:'Username and password required'},400);const role=['supervisor','employee'].includes(String(b.role))?String(b.role):'employee',sup=String(b.supervisor_username||'').trim();await env.DB.prepare("INSERT INTO governance_users(username,password,role,active,supervisor_username) VALUES (?,?,?,?,?)").bind(name,pass,role,1,role==='employee'?sup:'').run();await audit(env.DB,request.headers.get('x-governance-user')||'SuperAdmin','CREATE_USER',null,{username:name,role,supervisor_username:sup});return json({ok:true},201)}
   if(url.pathname==='/api/users/password'&&request.method==='PUT'){const b=await request.json(),u=String(b.username||''),old=String(b.oldPassword||''),nw=String(b.newPassword||'');if(!nw)return json({ok:false,error:'New password required'},400);const x=await env.DB.prepare('SELECT username FROM governance_users WHERE username=? AND password=? AND active=1').bind(u,old).first();if(!x)return json({ok:false,error:'Current password is incorrect'},401);await env.DB.prepare('UPDATE governance_users SET password=?,updated_at=CURRENT_TIMESTAMP WHERE username=?').bind(nw,u).run();return json({ok:true})}
   if(url.pathname==='/api/users/reset-password'&&request.method==='PUT'){
    const b=await request.json(),name=String(b.username||'').trim(),pass=String(b.password||'');
    if(!name||!pass)return json({ok:false,error:'Required'},400);
    const q=await env.DB.prepare('UPDATE governance_users SET password=?,active=1,updated_at=CURRENT_TIMESTAMP WHERE username=? COLLATE NOCASE RETURNING username,role,active').bind(pass,name).first();
    if(!q)return json({ok:false,error:'User not found'},404);
    await audit(env.DB,request.headers.get('x-governance-user')||'SuperAdmin','RESET_PASSWORD',null,{username:q.username});
    return json({ok:true,user:q});
   }
   if(url.pathname==='/api/users/status'&&request.method==='PUT'){const b=await request.json(),name=String(b.username||'');if(!name||name.toLowerCase()==='superadmin')return json({ok:false,error:'Not allowed'},400);await env.DB.prepare('UPDATE governance_users SET active=?,updated_at=CURRENT_TIMESTAMP WHERE username=?').bind(b.active?1:0,name).run();await audit(env.DB,request.headers.get('x-governance-user')||'SuperAdmin',b.active?'ENABLE_USER':'DISABLE_USER',null,{username:name});return json({ok:true})}
   const um=url.pathname.match(/^\/api\/users\/([^/]+)$/);if(um&&request.method==='DELETE'){const name=decodeURIComponent(um[1]);if(name.toLowerCase()==='superadmin')return json({ok:false,error:'Not allowed'},400);const actor=request.headers.get('x-governance-user')||'SuperAdmin',old=await env.DB.prepare('SELECT username,role FROM governance_users WHERE username=? COLLATE NOCASE').bind(name).first();if(!old)return json({ok:false,error:'User not found'},404);await env.DB.prepare("UPDATE governance_users SET supervisor_username='',updated_at=CURRENT_TIMESTAMP WHERE supervisor_username=? COLLATE NOCASE").bind(name).run();await env.DB.prepare('DELETE FROM governance_users WHERE username=? COLLATE NOCASE').bind(name).run();await audit(env.DB,actor,'DELETE_USER',null,{username:name,role:old.role,team_unassigned:true});return json({ok:true})}
   if(url.pathname==='/api/users/assignment'&&request.method==='PUT'){const b=await request.json(),name=String(b.username||'').trim(),role=['supervisor','employee'].includes(String(b.role))?String(b.role):'employee',sup=role==='employee'?String(b.supervisor_username||'').trim():'';if(!name||name.toLowerCase()==='superadmin')return json({ok:false,error:'Not allowed'},400);if(sup&&sup.toLowerCase()===name.toLowerCase())return json({ok:false,error:'User cannot supervise themselves'},400);if(sup){const valid=await env.DB.prepare("SELECT username FROM governance_users WHERE username=? COLLATE NOCASE AND role='supervisor' AND active=1").bind(sup).first();if(!valid)return json({ok:false,error:'Supervisor not found or inactive'},400)}const old=await env.DB.prepare('SELECT role,supervisor_username FROM governance_users WHERE username=? COLLATE NOCASE').bind(name).first();if(!old)return json({ok:false,error:'User not found'},404);if(role==='employee'&&old.role==='supervisor'){await env.DB.prepare("UPDATE governance_users SET supervisor_username='',updated_at=CURRENT_TIMESTAMP WHERE supervisor_username=? COLLATE NOCASE").bind(name).run()}const q=await env.DB.prepare('UPDATE governance_users SET role=?,supervisor_username=?,updated_at=CURRENT_TIMESTAMP WHERE username=? COLLATE NOCASE RETURNING username,role,supervisor_username').bind(role,sup,name).first();await audit(env.DB,request.headers.get('x-governance-user')||'SuperAdmin','ASSIGN_USER',null,{username:q.username,old_role:old.role,new_role:q.role,old_supervisor:old.supervisor_username,new_supervisor:q.supervisor_username,former_team_unassigned:old.role==='supervisor'&&role==='employee'});return json({ok:true,user:q})}
   if(url.pathname==='/api/evaluations'&&request.method==='GET'){const sup=String(url.searchParams.get('supervisor')||'').trim(),emp=String(url.searchParams.get('employee')||'').trim();let q;if(sup)q=await env.DB.prepare('SELECT * FROM governance_evaluations WHERE supervisor_username=? ORDER BY id DESC').bind(sup).all();else if(emp)q=await env.DB.prepare('SELECT * FROM governance_evaluations WHERE employee_username=? ORDER BY id DESC').bind(emp).all();else q=await env.DB.prepare('SELECT * FROM governance_evaluations ORDER BY id DESC LIMIT 1000').all();return json({ok:true,evaluations:q.results||[]})}
   if(url.pathname==='/api/evaluations'&&request.method==='DELETE'){const b=await request.json().catch(()=>({})),id=Number(b.id),sup=String(b.supervisor_username||request.headers.get('x-governance-user')||'').trim();if(!Number.isInteger(id)||id<1)return json({ok:false,error:'Invalid evaluation id'},400);const q=await env.DB.prepare('DELETE FROM governance_evaluations WHERE id=? AND supervisor_username=? COLLATE NOCASE RETURNING id,employee_username').bind(id,sup).first();if(!q)return json({ok:false,error:'Evaluation not found or not owned by supervisor'},404);await audit(env.DB,sup,'DELETE_EVALUATION',null,{evaluation_id:id,employee_username:q.employee_username});return json({ok:true,id});}
   if(url.pathname==='/api/evaluations'&&request.method==='POST'){const b=await request.json(),sup=String(b.supervisor_username||'').trim(),emp=String(b.employee_username||'').trim(),score=Number(b.score),notes=String(b.notes||'').trim();if(!sup||!emp||!Number.isFinite(score)||score<0||score>100)return json({ok:false,error:'Invalid evaluation'},400);const member=await env.DB.prepare("SELECT username FROM governance_users WHERE username=? COLLATE NOCASE AND role='employee' AND supervisor_username=? COLLATE NOCASE").bind(emp,sup).first();if(!member)return json({ok:false,error:'Employee is not assigned to this supervisor'},403);const existing=await env.DB.prepare('SELECT id FROM governance_evaluations WHERE supervisor_username=? COLLATE NOCASE AND employee_username=? COLLATE NOCASE ORDER BY id DESC LIMIT 1').bind(sup,emp).first();let q;if(existing){q=await env.DB.prepare('UPDATE governance_evaluations SET score=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=? RETURNING *').bind(score,notes.slice(0,500),existing.id).first();await audit(env.DB,sup,'UPDATE_EVALUATION',null,{evaluation_id:existing.id,employee_username:emp,score});}else{q=await env.DB.prepare('INSERT INTO governance_evaluations(supervisor_username,employee_username,score,notes) VALUES (?,?,?,?) RETURNING *').bind(sup,emp,score,notes.slice(0,500)).first();await audit(env.DB,sup,'EVALUATE_EMPLOYEE',null,{employee_username:emp,score});}return json({ok:true,evaluation:q},existing?200:201)}
   if(url.pathname==='/api/reports'&&request.method==='GET'){const owner=String(url.searchParams.get('owner')||'').trim(),role=String(request.headers.get('x-governance-role')||'').trim();let q;if(role==='superadmin'&&!owner)q=await env.DB.prepare('SELECT id,title,report_type,owner_username,owner_role,created_at,updated_at FROM governance_reports ORDER BY id DESC LIMIT 500').all();else q=await env.DB.prepare('SELECT id,title,report_type,owner_username,owner_role,created_at,updated_at FROM governance_reports WHERE owner_username=? COLLATE NOCASE ORDER BY id DESC LIMIT 200').bind(owner||request.headers.get('x-governance-user')||'').all();return json({ok:true,reports:q.results||[]})}
   if(url.pathname==='/api/reports'&&request.method==='POST'){const b=await request.json(),title=String(b.title||'').trim().slice(0,120),type=String(b.report_type||'snapshot').trim().slice(0,30),owner=String(request.headers.get('x-governance-user')||b.owner_username||'').trim(),role=String(request.headers.get('x-governance-role')||b.owner_role||'employee').trim(),payload=JSON.stringify(b.payload??{});if(!title||!owner)return json({ok:false,error:'Title and owner required'},400);if(payload.length>750000)return json({ok:false,error:'Report is too large'},413);const q=await env.DB.prepare('INSERT INTO governance_reports(title,report_type,owner_username,owner_role,payload) VALUES (?,?,?,?,?) RETURNING id,title,report_type,owner_username,owner_role,created_at,updated_at').bind(title,type,owner,role,payload).first();await audit(env.DB,owner,'SAVE_REPORT',null,{report_id:q.id,title});return json({ok:true,report:q},201)}
   const rep=url.pathname.match(/^\/api\/reports\/(\d+)$/);if(rep&&request.method==='GET'){const id=Number(rep[1]),q=await env.DB.prepare('SELECT * FROM governance_reports WHERE id=?').bind(id).first();if(!q)return json({ok:false,error:'Report not found'},404);let payload={};try{payload=JSON.parse(q.payload||'{}')}catch(e){}return json({ok:true,report:{...q,payload}})}
   if(rep&&request.method==='DELETE'){const id=Number(rep[1]),owner=String(request.headers.get('x-governance-user')||'').trim(),role=String(request.headers.get('x-governance-role')||'').trim();let q;if(role==='superadmin')q=await env.DB.prepare('DELETE FROM governance_reports WHERE id=? RETURNING id,title,owner_username').bind(id).first();else q=await env.DB.prepare('DELETE FROM governance_reports WHERE id=? AND owner_username=? COLLATE NOCASE RETURNING id,title,owner_username').bind(id,owner).first();if(!q)return json({ok:false,error:'Report not found or not allowed'},404);await audit(env.DB,owner,'DELETE_REPORT',null,{report_id:id,title:q.title});return json({ok:true,id})}
   if(url.pathname==='/api/audit'&&request.method==='GET'){const q=await env.DB.prepare('SELECT id,username,action,record_id,details,created_at FROM governance_audit ORDER BY id DESC LIMIT 500').all();return json({ok:true,logs:q.results||[]})}
   if(url.pathname==='/api/user-activity'&&request.method==='GET'){const name=String(url.searchParams.get('username')||'').trim();if(!name)return json({ok:false,error:'Username required'},400);const u=await env.DB.prepare('SELECT username,role,active,created_at,updated_at FROM governance_users WHERE username=?').bind(name).first();if(!u)return json({ok:false,error:'User not found'},404);const q=await env.DB.prepare('SELECT id,username,action,record_id,details,created_at FROM governance_audit WHERE username=? ORDER BY id DESC LIMIT 1000').bind(name).all();return json({ok:true,user:u,logs:q.results||[]})}
   if(!url.pathname.startsWith('/api/records')) return env.ASSETS.fetch(request);
   if(request.method==='GET'&&url.pathname==='/api/records'){
    const q=await env.DB.prepare('SELECT id,employee_name,employee_id,supervisor_name,record_date,notes,service_metrics,service,period,quality,csat,productivity,created_at,updated_at,saved_by FROM governance_records ORDER BY id DESC').all();
    return json({ok:true,records:(q.results||[]).map(row)});
   }
   if(request.method==='POST'&&url.pathname==='/api/records'){
    const b=await request.json(),v=clean(b); if(!v)return json({ok:false,error:'Invalid record'},400);const user=String(b.savedBy||'Admin');
    const q=await env.DB.prepare('INSERT INTO governance_records (employee_name,employee_id,supervisor_name,record_date,notes,service_metrics,service,period,quality,csat,productivity,created_at,updated_at,saved_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,?) RETURNING *').bind(v.employee_name,v.employee_id,v.supervisor_name,v.record_date,v.notes,v.service_metrics,v.service,v.period,v.quality,v.csat,v.productivity,user).first();await audit(env.DB,user,'CREATE',q.id,row(q));
    return json({ok:true,record:row(q)},201);
   }
   const m=url.pathname.match(/^\/api\/records\/(\d+)$/); if(!m)return json({ok:false,error:'Not found'},404);
   const id=Number(m[1]);
   if(request.method==='PUT'){
    const b=await request.json(),v=clean(b); if(!v)return json({ok:false,error:'Invalid record'},400);const user=String(b.savedBy||'Admin');
    const q=await env.DB.prepare('UPDATE governance_records SET employee_name=?,employee_id=?,supervisor_name=?,record_date=?,notes=?,service_metrics=?,service=?,period=?,quality=?,csat=?,productivity=?,updated_at=CURRENT_TIMESTAMP,saved_by=? WHERE id=? RETURNING *').bind(v.employee_name,v.employee_id,v.supervisor_name,v.record_date,v.notes,v.service_metrics,v.service,v.period,v.quality,v.csat,v.productivity,user,id).first();if(q)await audit(env.DB,user,'UPDATE',id,row(q));
    return q?json({ok:true,record:row(q)}):json({ok:false,error:'Record not found'},404);
   }
   if(request.method==='DELETE'){
    const q=await env.DB.prepare('DELETE FROM governance_records WHERE id=? RETURNING id').bind(id).first();
    if(q)await audit(env.DB,request.headers.get('x-governance-user')||'Admin','DELETE',id,{id});return q?json({ok:true,id}):json({ok:false,error:'Record not found'},404);
   }
   return json({ok:false,error:'Method not allowed'},405);
  }catch(e){return json({ok:false,error:'Database operation failed'},500)}
 }
};